BIN mapdata_startroom "mapdata/startroom.bin" 2 2 0
BIN mapdata_sidesquare "mapdata/sidesquare.bin" 2 2 0
BIN mapdata_teleroom "mapdata/teleroom.bin" 2 2 0
BIN mapdata_lefttall "mapdata/lefttall.bin" 2 2 0
BIN mapdata_plantroom "mapdata/plantroom.bin" 2 2 0
BIN mapdata_earlycorridor "mapdata/earlycorridor.bin" 2 2 0
BIN mapdata_cownspikes "mapdata/cownspikes.bin" 2 2 0
BIN mapdata_liftget "mapdata/liftget.bin" 2 2 0
BIN mapdata_earlybumps "mapdata/earlybumps.bin" 2 2 0
BIN mapdata_smallchamber "mapdata/smallchamber.bin" 2 2 0
BIN mapdata_zigzag "mapdata/zigzag.bin" 2 2 0
BIN mapdata_jumpget "mapdata/jumpget.bin" 2 2 0
BIN mapdata_lavatower "mapdata/lavatower.bin" 2 2 0
BIN mapdata_ballhall "mapdata/ballhall.bin" 2 2 0
BIN mapdata_kickblock "mapdata/kickblock.bin" 2 2 0
BIN mapdata_pillatower "mapdata/pillatower.bin" 2 2 0
BIN mapdata_buggozone "mapdata/buggozone.bin" 2 2 0
BIN mapdata_poweruptower "mapdata/poweruptower.bin" 2 2 0
BIN mapdata_boingotele "mapdata/boingotele.bin" 2 2 0
BIN mapdata_undersand "mapdata/undersand.bin" 2 2 0
BIN mapdata_spikeshelf "mapdata/spikeshelf.bin" 2 2 0
BIN mapdata_kickget "mapdata/kickget.bin" 2 2 0
BIN mapdata_cowzone "mapdata/cowzone.bin" 2 2 0
BIN mapdata_smallghetto "mapdata/smallghetto.bin" 2 2 0
BIN mapdata_flargycolumn "mapdata/flargycolumn.bin" 2 2 0
BIN mapdata_bigghetto "mapdata/bigghetto.bin" 2 2 0
BIN mapdata_elevatorroom "mapdata/elevatorroom.bin" 2 2 0
BIN mapdata_topleft "mapdata/topleft.bin" 2 2 0
BIN mapdata_dogtown "mapdata/dogtown.bin" 2 2 0
BIN mapdata_pyramid "mapdata/pyramid.bin" 2 2 0
BIN mapdata_basketball "mapdata/basketball.bin" 2 2 0
BIN mapdata_treesand "mapdata/treesand.bin" 2 2 0
BIN mapdata_purplezone "mapdata/purplezone.bin" 2 2 0
BIN mapdata_littlepurple "mapdata/littlepurple.bin" 2 2 0
BIN mapdata_orangeget "mapdata/orangeget.bin" 2 2 0
BIN mapdata_phantomget "mapdata/phantomget.bin" 2 2 0
BIN mapdata_boss1 "mapdata/boss1.bin" 2 2 0
BIN mapdata_rooftop "mapdata/rooftop.bin" 2 2 0
BIN mapdata_roofroom "mapdata/roofroom.bin" 2 2 0

BIN mapdata_roomzero "mapdata/roomzero.bin" 2 2 0
