BIN mapdata_roomzero "mapdata/roomzero.bin" 2 2 0
BIN mapdata_startroom "mapdata/startroom.bin" 2 2 0
BIN mapdata_sidesquare "mapdata/sidesquare.bin" 2 2 0
BIN mapdata_teleroom "mapdata/teleroom.bin" 2 2 0
BIN mapdata_lefttall "mapdata/lefttall.bin" 2 2 0
BIN mapdata_plantroom "mapdata/plantroom.bin" 2 2 0
BIN mapdata_earlycorridor "mapdata/earlycorridor.bin" 2 2 0
BIN mapdata_cownspikes "mapdata/cownspikes.bin" 2 2 0
BIN mapdata_liftget "mapdata/liftget.bin" 2 2 0
BIN mapdata_earlybumps "mapdata/earlybumps.bin" 2 2 0
BIN mapdata_smallchamber "mapdata/smallchamber.bin" 2 2 0
