BIN mapdata_startroom "mapdata/startroom.bin" 2 2 0
BIN mapdata_sidesquare "mapdata/sidesquare.bin" 2 2 0
BIN mapdata_teleroom "mapdata/teleroom.bin" 2 2 0
BIN mapdata_lefttall "mapdata/lefttall.bin" 2 2 0
BIN mapdata_plantroom "mapdata/plantroom.bin" 2 2 0
BIN mapdata_earlycorridor "mapdata/earlycorridor.bin" 2 2 0
BIN mapdata_cownspikes "mapdata/cownspikes.bin" 2 2 0
BIN mapdata_liftget "mapdata/liftget.bin" 2 2 0
BIN mapdata_earlybumps "mapdata/earlybumps.bin" 2 2 0
BIN mapdata_smallchamber "mapdata/smallchamber.bin" 2 2 0
BIN mapdata_zigzag "mapdata/zigzag.bin" 2 2 0
BIN mapdata_jumpget "mapdata/jumpget.bin" 2 2 0
BIN mapdata_lavatower "mapdata/lavatower.bin" 2 2 0
BIN mapdata_ballhall "mapdata/ballhall.bin" 2 2 0
BIN mapdata_kickblock "mapdata/kickblock.bin" 2 2 0
BIN mapdata_pillatower "mapdata/pillatower.bin" 2 2 0
BIN mapdata_buggozone "mapdata/buggozone.bin" 2 2 0
BIN mapdata_poweruptower "mapdata/poweruptower.bin" 2 2 0
BIN mapdata_boingotele "mapdata/boingotele.bin" 2 2 0
BIN mapdata_undersand "mapdata/undersand.bin" 2 2 0

BIN mapdata_roomzero "mapdata/roomzero.bin" 2 2 0
