BIN sfx_jump "sfx/jump.esf" 2 2 0
BIN sfx_walk1 "sfx/walk1.esf" 2 2 0
BIN sfx_walk2 "sfx/walk2.esf" 2 2 0
BIN sfx_cubetoss "sfx/cubetoss.esf" 2 2 0
BIN sfx_cubebounce "sfx/cubebounce.esf" 2 2 0
BIN sfx_fizzle "sfx/fizzle.esf" 2 2 0
BIN sfx_cubespawn "sfx/cubespawn.esf" 2 2 0
BIN sfx_enemyexplode "sfx/enemyexplode.esf" 2 2 0
BIN sfx_enemystrike "sfx/enemystrike.esf" 2 2 0
BIN sfx_pause "sfx/pause.esf" 2 2 0
