#ifndef ENEMY_TYPES_H
#define ENEMY_TYPES_H

// Enemy type numbers -- these line up to MAP_OBJ numbers intentionally
#define ENEMY_NULL 0
#define ENEMY_METAGRUB 3
#define ENEMY_FLIP 4
#define ENEMY_BOINGO 5
#define ENEMY_ITEM 6
#define ENEMY_GAXTER1 7
#define ENEMY_GAXTER2 8
#define ENEMY_BUGGO1 9
#define ENEMY_BUGGO2 10
#define ENEMY_DANCYFLOWER 11
#define ENEMY_JRAFF 12
#define ENEMY_PILLA 13
#define ENEMY_HEDGEDOG 14
#define ENEMY_SHOOT 15
#define ENEMY_LASER 16
#define ENEMY_KILLZAM 17
#define ENEMY_FLARGY 18
#define ENEMY_PLANT 19
#define ENEMY_TOSSMUFFIN 20
#define ENEMY_TELEPORTER 21
#define ENEMY_MAGIBEAR 22
#define ENEMY_LAVA 23
#define ENEMY_COW 24
#define ENEMY_CONTAINER 25
#define ENEMY_HOOP 26
#define ENEMY_FALSEBLOCK 27
#define ENEMY_CP_PAD 28
#define ENEMY_CP_METER 29
#define ENEMY_DOG 30
#define ENEMY_ELEVATOR 31
#define ENEMY_ELEVATOR_STOP 32
#define ENEMY_FISSINS1 33
#define ENEMY_BOSS1 34
#define ENEMY_BOSS2 35
#define ENEMY_BOSSF1 36
#define ENEMY_BOSSF2 37
#define ENEMY_EGG 38
#define ENEMY_FISSINS2 39
#define ENEMY_BOUNDS 40
#define ENEMY_SMALLEGG 41
#define ENEMY_BASKETBALL 42
#define ENEMY_LAVAANIM 43
#define ENEMY_SPOOKO 44
#define ENEMY_WIP 45
// ---------------------


#endif
